Introducing: Perltidy rule for consistent space before signatures
os-autoinst/os-autoinst-common pull request #35
Opened 2024-01-22 16:45 UTC by josegomezr

Perl-tidy native rule to enforce "Consistent space before function signatures (this is not ensured by perltidy)" rule in Makefiles in openQA & os-autoinst.

2024-01-22 20:28 UTC, okurz requested changes

2024-01-22 20:38 UTC, josegomezr commented on lib/perlcritic/Perl/Critic/Policy/SpaceAfterSubroutineName.pm
> +use Data::Dumper;
Nice catch

2024-01-22 20:38 UTC, josegomezr commented on lib/perlcritic/Perl/Critic/Policy/SpaceAfterSubroutineName.pm
> +    return;
Noting

2024-01-22 20:46 UTC, josegomezr commented
@okurz `return undef` breaks with:

```
Fatal error while critiquing "lib/perlcritic/Perl/Critic/Policy/ArgumentInUseStrictWarnings.pm": Can't call method "location" on an undefined value at /home/josegomezr/perl5/lib/perl5/Perl/Critic.pm line 175.
```

I'll revert it.

2024-01-22 21:20 UTC, josegomezr commented
I believe the latest rework @ [f6971a0](https://github.com/os-autoinst/os-autoinst-common/pull/35/commits/f6971a00ef3eb721a96e2b3786aebb2ce6463cec) makes it more straight forward

2024-01-22 21:36 UTC, okurz approved these changes

2024-01-23 09:01 UTC, kalikiana approved these changes

2024-01-23 09:01 UTC, merged

2024-01-23 17:41 UTC, perlpunk commented
btw, this PR talks about perltidy, but it is about perlcritic.

2024-01-23 17:42 UTC, josegomezr commented
Ouh, just noticed it :sweat: I'll update the title although so long for the commit :sweat_smile: