Properly handle Scheduled routines with SpaceAfterSubroutineName
os-autoinst/os-autoinst-common pull request #36
Opened 2024-01-23 10:15 UTC by josegomezr

- The rule now handles reserved SUB's (END, BEGIN, & friends) correctly.

- Documented the token layout for each case.

2024-01-23 10:15 UTC, josegomezr commented
This is a refinement for #35

2024-01-23 10:35 UTC, perlpunk requested changes
Can you test this change on os-autoinst/os-autoinst? e.g. subrepo pull the branch and run the new perlcritic?

2024-01-23 10:58 UTC, Martchus commented
Looks good but it would indeed make sense to test it in one of the downstream repositories.

2024-01-23 11:37 UTC, perlpunk commented
I tested it with the current os-autoinst-common master and got an error (the perlcritic module died), so it's good to test a new version as well.
I tested this PR and got a lot of
```
::warning file=t/26-video_stream.t,line=168,col=52,title=Useless interpolation of literal string - severity 3::[ValuesAndExpressions::ProhibitInterpolationOfLiterals] See page 51 of PBP
...
```
but also several errors that might be wrong:
```
::warning file=myjsonrpc.pm,line=128,col=1,title=Inconsistent sub declaration - severity 5::[SpaceAfterSubroutineName] Sub 'TO_JSON' must have only one space surrounding name, parenthesis and/or block body
::warning file=os-autoinst-openvswitch,line=21,col=1,title=Superfluoux use of strict/warning - severity 5::[RedundantStrictWarning] use Mojo::Base 'Net::DBus::Object', -signatures; is equivalent to 'use strict;
 use warnings;'                                                                                                                                                                                                   
...
::warning file=OpenQA/Qemu/DriveDevice.pm,line=163,col=1,title=Inconsistent sub declaration - severity 5::[SpaceAfterSubroutineName] Sub 'CARP_TRACE' must have only one space surrounding name, parenthesis and/o
r block body                                                                                                                                                                                                      
...
::warning file=backend/console_proxy.pm,line=22,col=1,title=Inconsistent sub declaration - severity 5::[SpaceAfterSubroutineName] Sub 'DESTROY' must have only one space surrounding name, parenthesis and/or bloc
k body                                                                                                                                                                                                            
::warning file=backend/console_proxy.pm,line=27,col=1,title=Inconsistent sub declaration - severity 5::[SpaceAfterSubroutineName] Sub 'AUTOLOAD' must have only one space surrounding name, parenthesis and/or blo
ck body                                                                                                                                                                                                           
...
::warning file=consoles/virtio_terminal.pm,line=99,col=1,title=Inconsistent sub declaration - severity 5::[SpaceAfterSubroutineName] Sub 'F_GETPIPE_SZ' must have only one space surrounding name, parenthesis and
/or block body                                                                                                                                                                                                    
::warning file=consoles/virtio_terminal.pm,line=105,col=1,title=Inconsistent sub declaration - severity 5::[SpaceAfterSubroutineName] Sub 'F_SETPIPE_SZ' must have only one space surrounding name, parenthesis an
d/or block body                                                                                                                                                                                                   
...
::warning file=consoles/s3270.pm,line=351,col=1,title=Inconsistent sub declaration - severity 5::[SpaceAfterSubroutineName] Sub 'DESTROY' must have only one space surrounding name, parenthesis and/or block body
...
::warning file=t/08-autotest.t,line=32,col=1,title=Inconsistent sub declaration - severity 5::[SpaceAfterSubroutineName] Sub 'loadtest' must have only one space surrounding name, parenthesis and/or block body
```
Also:
```
::warning file=backend/console_proxy.pm,line=33,col=5,title=Stricture disabled - severity 5::[TestingAndDebugging::ProhibitNoStrict] See page 429 of PBP
```
code:
```
no strict 'refs';
*$AUTOLOAD = sub {    # no:style:signatures
```
I guess we would have to turn perlcritic off for such lines then.

2024-01-23 12:25 UTC, josegomezr commented
Woah! Thanks for the output @perlpunk. I'll have a look now.

My initial suspicion is that all of them are in uppercase, but `loadtest` is not... :thinking: I'll report back with some findings

2024-01-23 12:55 UTC, josegomezr commented
So `->reserved` means that a sub name is all uppercase, it doens't check against any list. This is an easy fix.

The second one though, what a weird result I get from the parse tree:

```
sub loadtest ($test, $msg = "loadtest($test)") {
    my $filename = $test =~ /\.p[my]$/ ? $test : $test . '.pm';
    $test =~ s/\.p[my]//;
    stderr_like { autotest::loadtest "tests/$filename" } qr@scheduling $test#?[0-9]* tests/$test|$test already scheduled@, $msg;
}
```

returns the following tokens
```
$VAR1 = [
          'PPI::Token::Word: \'sub\'',
          'PPI::Token::Whitespace: \' \'',
          'PPI::Token::Word: \'loadtest\'',
          'PPI::Token::Whitespace: \' \'',
          'PPI::Token::Prototype: \'($test, $msg = "loadtest($test)\'',
          'PPI::Token::Quote::Double: \'") {
    my $filename = $test =~ /\\.p[my]$/ ? $test : $test . \'.pm\';
    $test =~ s/\\.p[my]//;
    stderr_like { autotest::loadtest "\'',
          'PPI::Token::Word: \'tests\''
        ];
```

but if I remove the default value from `$msg`:

```
$VAR1 = [
          'loadtest',
          'PPI::Token::Word: \'sub\'',
          'PPI::Token::Whitespace: \' \'',
          'PPI::Token::Word: \'loadtest\'',
          'PPI::Token::Whitespace: \' \'',
          'PPI::Token::Prototype: \'($test, $msg)\'',
          'PPI::Token::Whitespace: \' \'',
          'PPI::Token::Structure: \'{\''
        ];
```

Looks like an upstream bug (?) prototype is not being parsed correctly

2024-01-23 13:21 UTC, Martchus commented
I find it a bit weird that signatures show up as prototypes here. Regardless of that it looks indeed inconsistent and maybe is an upstream bug. However, I'm really not into that tooling so I guess I cannot help much.

2024-01-23 14:20 UTC, perlpunk commented
Signatures were an experimental feature for a long time, with some changes how they work until they got non-experimental. And due to perl's mechanism to enable features dynamically it's hard to distinguish them from prototypes.
Here are two github links:
* https://github.com/Perl-Critic/PPI/issues/194
* https://github.com/Perl-Critic/PPI/pull/280

So for now we have to live with that.
The original feature was just ensuring that there is a space after the subroutine name. Can we do that with perlcritic easily? Otherwise, as I also said before, I propose to use the existing perl script which has served us well enough ;-)

2024-01-23 14:26 UTC, josegomezr commented
With [cc00afb](https://github.com/os-autoinst/os-autoinst-common/pull/36/commits/cc00afb89cec934bf9649023f6161c0e35a0722c) I only get the parse failure one. I'll give it a bit more time, if I can't make it today I'll disable this rule and yank the `git grep` from the downstream repos

2024-01-23 14:41 UTC, josegomezr commented
Just ran the commit in isotovideo with:

```
./tools/perlcritic ../os-autoinst/ | grep -v 'source OK' | egrep -o 'severity.+]' | sort | uniq -c
      1 severity 3::[Miscellanea::ProhibitUnrestrictedNoCritic]
   1003 severity 3::[ValuesAndExpressions::ProhibitInterpolationOfLiterals]
      1 severity 4::[ControlStructures::ProhibitDeepNests]
      1 severity 4::[Variables::ProhibitConditionalDeclarations]
      4 severity 5::[HashKeyQuotes]
     64 severity 5::[RedundantStrictWarning]
      1 severity 5::[TestingAndDebugging::ProhibitNoStrict]
```

Looks good from the distance :thinking:

2024-02-07 13:03 UTC, perlpunk commented
See https://github.com/os-autoinst/os-autoinst-common/issues/48
I assume other perlcritic rules on CPAN have a lot of tests.
If we are adding our own rules, they might break on certain code.
Can you test this version on Perl/Tidy.pm?

2024-02-07 14:13 UTC, josegomezr commented
>  Can you test this version on Perl/Tidy.pm?

Here it is, it runs successfully (before rebasing):

```
📅2024-02-07🕙15:07:42 ➜ git rev-parse @
a9c61b9f7c8f2cd2de93a84309da92df15418d57

📅2024-02-07🕙15:07:43 ➜ ./tools/perlcritic Tidy.pm | egrep -v 'ProhibitInterpolationOfLiterals|HashKeyQuotes|ProhibitDeepNests'
# exit 0
```

After rebasing we get #42 benefit's and it looks like:

```
📅2024-02-07🕙15:11:25 ✗ ./tools/perlcritic Tidy.pm | egrep -v 'ProhibitInterpolationOfLiterals|ProhibitDeepNests'
::warning file=Tidy.pm,line=670,col=42,title=Hash key with quotes - severity 5::[HashKeyQuotes] Avoid useless quotes for key "argv"
::warning file=Tidy.pm,line=671,col=42,title=Hash key with quotes - severity 5::[HashKeyQuotes] Avoid useless quotes for key "destination"
::warning file=Tidy.pm,line=672,col=42,title=Hash key with quotes - severity [...]
::warning file=Tidy.pm,line=4954,col=23,title=Hash key with quotes - severity 5::[HashKeyQuotes] Avoid useless quotes for key "tabs"
::warning file=Tidy.pm,line=4960,col=22,title=Hash key with quotes - severity 5::[HashKeyQuotes] Avoid useless quotes for key "tabs"
```

2024-02-07 15:12 UTC, perlpunk approved these changes

2024-02-07 15:35 UTC, okurz approved these changes

2024-02-07 15:35 UTC, merged